In [ ]:
3+4

7

In [ ]:
#write a code to convert celcius to fahrenheit
# Input temperature in Celsius
celsius = float(input("Enter temperature in Celsius: "))

# Convert Celsius to Fahrenheit
fahrenheit = (celsius * 9 / 5) + 32

# Display the result
print(f"{celsius}°C is equal to {fahrenheit}°F")


Enter temperature in Celsius: 10
10.0°C is equal to 50.0°F


In [ ]:
#create a boolean variable for carbon footprint


In [ ]:
climate_data = [
    {"city": "City A", "temperature": 25, "carbon_footprint": 500},
    {"city": "City B", "temperature": 30, "carbon_footprint": 350},
    {"city": "City C", "temperature": 22, "carbon_footprint": 600},
    {"city": "City D", "temperature": 15, "carbon_footprint": 200},
    {"city": "City E", "temperature": 28, "carbon_footprint": 450},
]
high_temp_threshold=22
high_temp_cities=[city for city in climate_data if city["temperature"]>high_temp_threshold]
print("Cities with higher temperatures (>26 degree cel):")
for city in high_temp_cities:
  print(f"{city['city']}-{city['temperature']} degree cel")



Cities with higher temperatures (>26 degree cel):
City A-25 degree cel
City B-30 degree cel
City E-28 degree cel


In [ ]:
climate_data = [
    {"city": "City A", "temperature": 25, "carbon_footprint": 500},
    {"city": "City B", "temperature": 30, "carbon_footprint": 350},
    {"city": "City C", "temperature": 22, "carbon_footprint": 600},
    {"city": "City D", "temperature": 15, "carbon_footprint": 200},
    {"city": "City E", "temperature": 28, "carbon_footprint": 450},
]
 #write the code to find the city with highest carbon footprint
highest_carbon_footprint=0
for city in climate_data:
  if city["carbon_footprint"]>highest_carbon_footprint:
    highest_carbon_footprint=city["carbon_footprint"]
    city_with_highest_carbon_footprint=city["city"]
print(f"\n city with the highest carbon footprint:")
print(f"City with highest carbon footprint:{city_with_highest_carbon_footprint} kg CO2")




 city with the highest carbon footprint:
City with highest carbon footprint:City C kg CO2


In [ ]:
climate_data = [
    {"city": "City A", "temperature": 25, "carbon_footprint": 500},
    {"city": "City B", "temperature": 30, "carbon_footprint": 350},
    {"city": "City C", "temperature": 22, "carbon_footprint": 600},
    {"city": "City D", "temperature": 15, "carbon_footprint": 200},
    {"city": "City E", "temperature": 28, "carbon_footprint": 450},
]
# write a function to filter the city are sustainable or not(400 ton co2)
def is_sustainable(city):
  return city["carbon_footprint"]<=400

sustainable_cities=[city for city in climate_data if is_sustainable(city)]
print("Sustainable cities:")
for city in sustainable_cities:
  print(f"{city['city']}-{city['carbon_footprint']} kg CO2")


Sustainable cities:
City B-350 kg CO2
City D-200 kg CO2


In [ ]:
climate_data = [
    {"city": "City A", "temperature": 25, "carbon_footprint": 500},
    {"city": "City B", "temperature": 30, "carbon_footprint": 350},
    {"city": "City C", "temperature": 22, "carbon_footprint": 600},
    {"city": "City D", "temperature": 15, "carbon_footprint": 200},
    {"city": "City E", "temperature": 28, "carbon_footprint": 450},
]
# write a function to filter the city are sustainable or not(400 ton co2) use if else
def is_sustainable(city):
  if city["carbon_footprint"]<=400:
    return True
  else:
    return False

In [ ]:
# to check the given year is a leap year or not use the lambda function
is_leap_year = lambda year: (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0)
year = int(input("Enter a year: "))
if is_leap_year(year):
    print(f"{year} is a leap year.")
else:
    print(f"{year} is not a leap year.")


Enter a year: 2005
2005 is not a leap year.


In [ ]:
#calculate the average carbon footprint using loop
total_carbon_footprint=0
for city in climate_data:
  total_carbon_footprint+=city["carbon_footprint"]
average_carbon_footprint=total_carbon_footprint/len(climate_data)
print(f"Average carbon footprint:{average_carbon_footprint}")


Average carbon footprint:420.0


In [ ]:
#check the input function digit or not?
a=input()
if a.isdigit():
    print("it is a digit")
else:
    print("it is not a digit")

p
it is not a digit


In [ ]:
#use the identify operator to check the input function digit or not?
# Input from user
user_input = input("Enter something: ")

# Manual check for digits using identity operator
is_digit = True  # Assume it is a digit initially
for char in user_input:
    if char not in "0123456789":  # Check if character is not a digit
        is_digit = False
        break

# Output result
if is_digit is True:
    print(f"The input '{user_input}' is a digit.")
else:
    print(f"The input '{user_input}' is not a digit.")


Enter something: nkj
The input 'nkj' is not a digit.


In [ ]:
#take a input and check if any element of the list is present in the list
a=[1,2,3,4,5]
#take a input and check if any element of the list is present in the list
a=[1,2,3,4,5]
b=[1,2,3,4]
i=input()
print(any(i not in a for i in b))

0
False


In [ ]:
#create a calculator
print("Welcome to Calculator zone !")

while True:
    num1 = float(input("Enter the first number: "))
    operator = input("Enter the operator (+, -, *, /): ")
    num2 = float(input("Enter the second number: "))

    if operator == "+":
        result = num1 + num2
    elif operator == "-":
        result = num1 - num2
    elif operator == "*":
        result = num1 * num2
    elif operator == "/":
        result = num1 / num2
    else:
        print("Invalid operator!")
        continue

    print(f"Result: {num1} {operator} {num2} = {result}")
    choice = input("Do you want to perform another calculation? (yes/no): ")
    if choice.lower() != "yes":
        break

print("Thank you for using Calculator zone!")

Welcome to Calculator zone !
Enter the first number: 5
Enter the operator (+, -, *, /): +
Enter the second number: 5
Result: 5.0 + 5.0 = 10.0
Do you want to perform another calculation? (yes/no): no


# **3.Filter and Manipulate Data to find sustainable cities**

In [ ]:
import pandas as pd
renewable_sources=["Solar", "Wind", "Hydropower", "Geothrmal","Biomass"]
data = {
    "Project": ["Solar Farm A", "Wind Turbine X", "Hydropower Y", "Solar Roof Z", "Geothermal Plant P"],
    "Technology": ["Solar", "Wind", "Hydropower", "Solar", "Geothermal"],
    "Capacity (MW)": [150, 300, 200, 50, 100],  # Megawatts
    "Cost (Million $)": [200, 400, 350, 100, 250],  # Project cost
    "Location": ["California", "Texas", "Washington", "Nevada", "Idaho"],
    "Completion Year": [2023, 2024, 2022, 2025, 2023]
}

In [ ]:
renewable_series=pd.Series(renewable_sources)
print("renewable sources:")
print(renewable_series)

renewable sources:
0         Solar
1          Wind
2    Hydropower
3     Geothrmal
4       Biomass
dtype: object


In [ ]:
project_df=pd.DataFrame(data)
project_df.head()
print("Project DataFrame:")
print(project_df)

Project DataFrame:
              Project  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof Z       Solar             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  
0  California             2023  
1       Texas             2024  
2  Washington             2022  
3      Nevada             2025  
4       Idaho             2023  


In [ ]:
print(project_df.iloc[1:3])

          Project  Technology  Capacity (MW)  Cost (Million $)    Location  \
1  Wind Turbine X        Wind            300               400       Texas   
2    Hydropower Y  Hydropower            200               350  Washington   

   Completion Year  
1             2024  
2             2022  


In [ ]:
# filterout data where capacity more than 100
filtered_df=project_df[project_df["Capacity (MW)"]>100]
print("Filtered DataFrame:")
print(filtered_df)


Filtered DataFrame:
          Project  Technology  Capacity (MW)  Cost (Million $)    Location  \
0    Solar Farm A       Solar            150               200  California   
1  Wind Turbine X        Wind            300               400       Texas   
2    Hydropower Y  Hydropower            200               350  Washington   

   Completion Year  
0             2023  
1             2024  
2             2022  


In [ ]:
import pandas as pd

# Data
data = {
    "Project": ["Solar Farm A", "Wind Turbine X", "Hydropower Y", "Solar Roof Z", "Geothermal Plant P"],
    "Technology": ["Solar", "Wind", "Hydropower", "Solar", "Geothermal"],
    "Capacity (MW)": [150, 300, 200, 50, 100],  # Megawatts
    "Cost (Million $)": [200, 400, 350, 100, 250],  # Project cost
    "Location": ["California", "Texas", "Washington", "Nevada", "Idaho"],
    "Completion Year": [2023, 2024, 2022, 2025, 2023]
}

# Create the DataFrame
projects_df = pd.DataFrame(data)

# Add a new column for Cost per MW
projects_df["Cost per MW (Million $)"] = projects_df["Cost (Million $)"] / projects_df["Capacity (MW)"]

print(projects_df)

              Project  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof Z       Solar             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  Cost per MW (Million $)  
0  California             2023                 1.333333  
1       Texas             2024                 1.333333  
2  Washington             2022                 1.750000  
3      Nevada             2025                 2.000000  
4       Idaho             2023                 2.500000  


In [ ]:
import pandas as pd

# Data
data = {
    "Project": ["Solar Farm A", "Wind Turbine X", "Hydropower Y", "Solar Roof Z", "Geothermal Plant P"],
    "Technology": ["Solar", "Wind", "Hydropower", "Solar", "Geothermal"],
    "Capacity (MW)": [150, 300, 200, 50, 100],  # Megawatts
    "Cost (Million $)": [200, 400, 350, 100, 250],  # Project cost
    "Location": ["California", "Texas", "Washington", "Nevada", "Idaho"],
    "Completion Year": [2023, 2024, 2022, 2025, 2023]
}

# Create the DataFrame
projects_df = pd.DataFrame(data)

# Add a new column for Cost per MW
projects_df["Cost per MW (Million $)"] = projects_df["Cost (Million $)"] / projects_df["Capacity (MW)"]

#group by technology and calculate total capacity for each type
grouped_data=projects_df.groupby("Technology")["Capacity (MW)"].sum()
print("Total Capacity by Technology:")
print(grouped_data)

Total Capacity by Technology:
Technology
Geothermal    100
Hydropower    200
Solar         200
Wind          300
Name: Capacity (MW), dtype: int64


In [ ]:
import numpy as np
#one dimension array
arr=np.array([1,2,3,4,5])
print(arr)
#create a two dimension array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [ ]:
#print the shape of one dimension array
arr=np.array([1,2,3,4,5])
print(arr.shape)
#create a two dimension array
#print the shape of one dimension array
one_d_array=np.array([1,2,3])
print(one_d_array.shape)
two_d_array=np.array([[1,2,3],[4,5,6]])
print(two_d_array.shape)
#check the dimension of array
print(one_d_array.ndim)
print(two_d_array.ndim)
#create a default 1d array of integer
arr=np.arange(10)
print(arr)
#create a default 1d array of float
arr=np.arange(10,dtype=float)
print(arr)
#use of item size to determine size of each element
print(arr.itemsize)
#use of dtype to determine data type of array
print(arr.dtype)
#use of size to determine total number of elements in array
print(arr.size)
#use of astype to convert data type of array
arr=arr.astype(str)
print(arr.dtype)

(5,)
(3,)
(2, 3)
1
2
[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
8
float64
10
<U32


In [ ]:
#ones(),zeros(),random()
arr=np.ones((3,3))
print(arr)
arr=np.zeros((3,3))
print(arr)
arr=np.random.random((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0.98777584 0.41712777 0.80995524]
 [0.74834533 0.67462795 0.37855013]
 [0.84299463 0.09593257 0.4700629 ]]


In [ ]:
#create an array 3cross3 array where all the elements are 10 use np full
arr=np.full((3,3),10)
print(arr)
#create an array 3cross3 array where all the elements are 0 use np full
arr=np.full((3,3),0)
print(arr)
#print the identity matrix
arr=np.identity(3)
print(arr)


[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#arrange the values from 0 to 10
arr=np.arange(11)
print(arr)
#arrange the values from 10 to 1
arr=np.arange(10,0,-1)
print(arr)
#try out line space array
arr=np.linspace(5,10,3)
print(arr)
#try out log space array
arr=np.logspace(0,10,5)
print(arr)
#try out log space array
arr=np.logspace(0,10,5,base=2)
print(arr)
#try out log space array
arr=np.logspace(0,10,5,base=3)

[ 0  1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]
[ 5.   7.5 10. ]
[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10]
[1.00000000e+00 5.65685425e+00 3.20000000e+01 1.81019336e+02
 1.02400000e+03]


In [ ]:
#create one array and use the step as 1,2,3
arr=np.arange(1,10,2)
print(arr)
#print all the elements of array
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr)
#use step size=1
print(arr[::1])
#use the size=2
print(arr[::2])
#use the size=3
print(arr[::3])
#print all the elements in reverse order
print(arr[::-1])


[1 3 5 7 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[1 4 7]
[9 8 7 6 5 4 3 2 1]


In [ ]:
#check wheather the string is palidrome or not
string=input()
if string==string[::-1]:
  print("it is a palidrome")
else:
  print("it is not a palidrome")

121
it is a palidrome


In [ ]:
#use the reshape
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr.reshape(3,3))



[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#find the transpose of array
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.T)

In [ ]:
#find the mean,median,mode
arr=np.array([1,2,3,4,5,6,7,8,9])
print(np.mean(arr))
print(np.median(arr))
print(np.mode(arr))

In [ ]:
# Filter
high_capacity_projects=projects_df[projects_df["Capacity (MW)"]>100]
# print(high_capacity_projects)
high_capacity_projects.head()
# print(type(high_capacity_projects))

# Cost per MW
projects_df["Cost_per_MW"]=projects_df["Cost (Million $)"]/projects_df["Capacity (MW)"]

# **DATA HANDLING**

In [ ]:
import pandas as pd
import numpy as np
data = {
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [200, 400, np.nan, 150, 250, np.nan]
}
df = pd.DataFrame(data)
energy_df=pd.DataFrame(data)


In [ ]:
#remove rows with any missing values
energy_df=pd.DataFrame(data)
energy_df.dropna(axis=0,inplace=True)
energy_df.head()


Project  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof Z       Solar             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  
0  California             2023  
1       Texas             2024  
2  Washington             2022  
3      Nevada             2025  
4       Idaho             2023

from matplotlib import pyplot as plt
_df_0['Capacity (MW)'].plot(kind='hist', bins=20, title='Capacity (MW)')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['Cost (Million $)'].plot(kind='hist', bins=20, title='Cost (Million $)')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['Completion Year'].plot(kind='hist', bins=20, title='Completion Year')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_3.groupby('Project').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_4.groupby('Technology').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_5.groupby('Location').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='Capacity (MW)', y='Cost (Million $)', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='Cost (Million $)', y='Completion Year', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_8['Capacity (MW)'].plot(kind='line', figsize=(8, 4), title='Capacity (MW)')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_9['Cost (Million $)'].plot(kind='line', figsize=(8, 4), title='Cost (Million $)')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_10['Completion Year'].plot(kind='line', figsize=(8, 4), title='Completion Year')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Technology'].value_counts()
    for x_label, grp in _df_11.groupby('Project')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Project')
_ = plt.ylabel('Technology')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Location'].value_counts()
    for x_label, grp in _df_12.groupby('Technology')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Technology')
_ = plt.ylabel('Location')

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_13['Project'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_13, x='Capacity (MW)', y='Project', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_14['Technology'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_14, x='Capacity (MW)', y='Technology', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_15['Location'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_15, x='Capacity (MW)', y='Location', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_16['Project'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_16, x='Cost (Million $)', y='Project', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
#write the code with missing value to mean
ec_mean=energy_df["Energy Consumption (MWh)"].mean()
energy_df["Energy Consumption (MWh)"].fillna(ec_mean,inplace=True)
print(energy_df)


In [ ]:
#forward fill missing fill
forward_filled_df = energy_df.fillna(method="ffill")
print("\nData Before foreward filling:")
print(energy_df)
print("\nData After forward filling:")
forward_filled_df.head()


Data Before foreward filling:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                       NaN             400.0
2    Hydropower                    2900.0               NaN
3    Geothermal                       NaN             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN

Data After forward filling:


<ipython-input-25-bff71d6d3da4>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  forward_filled_df = energy_df.fillna(method="ffill")


Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                    1200.0             400.0
2    Hydropower                    2900.0             400.0
3    Geothermal                    2900.0             150.0
4       Biomass                    2500.0             250.0

In [ ]:
# Create a flag column indicating missing values in 'Energy Consumption (MWh)'
energy_df["Missing Consumption"] = energy_df["Energy Consumption (MWh)"].isna().astype(int)
energy_df["Missing Cost"] = energy_df["Cost (Million $)"].isna().astype(int)

print("\nData with Missing Values Flagged:")
energy_df.head()


Data with Missing Values Flagged:


Energy Source  Energy Consumption (MWh)  Cost (Million $)  \
0         Solar                    1200.0             200.0   
1          Wind                       NaN             400.0   
2    Hydropower                    2900.0               NaN   
3    Geothermal                       NaN             150.0   
4       Biomass                    2500.0             250.0   

   Missing Consumption  Missing Cost  
0                    0             0  
1                    1             0  
2                    0             1  
3                    1             0  
4                    0             0

In [ ]:
import pandas as pd
import numpy as np
data = {
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [200, 400, np.nan, 150, 250, np.nan]
}
energy_df = pd.DataFrame(data)


# Calculate the mean of 'Cost (Million $)' and 'Energy Consumption (MWh)'
cost_mean = energy_df['Cost (Million $)'].mean()
ec_mean = energy_df['Energy Consumption (MWh)'].mean()

# Fill NaN values with the calculated means
energy_df['Cost (Million $)'].fillna(cost_mean, inplace=True)
energy_df['Energy Consumption (MWh)'].fillna(ec_mean, inplace=True)

# Calculate and print the mean of the columns.
print(energy_df['Cost (Million $)'].mean())
print(energy_df['Energy Consumption (MWh)'].mean())

250.0
2450.0


<ipython-input-33-096e3d269fbb>:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  energy_df['Cost (Million $)'].fillna(cost_mean, inplace=True)
<ipython-input-33-096e3d269fbb>:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=T

In [ ]:
import pandas as pd
import numpy as np
data = {
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [200, 400, np.nan, 150, 250, np.nan]
}
energy_df = pd.DataFrame(data)


# Calculate the mean of 'Cost (Million $)' and 'Energy Consumption (MWh)'
cost_mean = energy_df['Cost (Million $)'].mean()
ec_mean = energy_df['Energy Consumption (MWh)'].mean()

# Fill NaN values with the calculated means
energy_df['Cost (Million $)'].fillna(cost_mean, inplace=True)
energy_df['Energy Consumption (MWh)'].fillna(ec_mean, inplace=True)
print(energy_df.head())

  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                    2450.0             400.0
2    Hydropower                    2900.0             250.0
3    Geothermal                    2450.0             150.0
4       Biomass                    2500.0             250.0


<ipython-input-32-3345846e5dc1>:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  energy_df['Cost (Million $)'].fillna(cost_mean, inplace=True)
<ipython-input-32-3345846e5dc1>:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=T

In [ ]:
#DATA PREPROCESSING
xmin_ec = np.min(energy_df["Energy Consumption (MWh)"])
xmax_ec = np.max(energy_df["Energy Consumption (MWh)"])
print("Minimum Energy Consumption: ", xmin_ec)
print("Maximum Energy Consumption: ", xmax_ec)

Minimum Energy Consumption:  -1.637804455201046
Maximum Energy Consumption:  0.9826826731206276


In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
energy_df[["Energy Consumption (MWh)", "Cost (Million $)"]] = scaler.fit_transform(energy_df[["Energy Consumption (MWh)", "Cost (Million $)"]])

print("\nData After Min-Max Scaling:")
print(energy_df)


Data After Min-Max Scaling:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)  \
0         Solar                      0.00               0.2   
1          Wind                       NaN               1.0   
2    Hydropower                      0.85               NaN   
3    Geothermal                       NaN               0.0   
4       Biomass                      0.65               0.4   
5       Nuclear                      1.00               NaN   

   Missing Consumption  Missing Cost  
0                    0             0  
1                    1             0  
2                    0             1  
3                    1             0  
4                    0             0  
5                    0             1  


In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
energy_df[["Energy Consumption (MWh)","Cost (Million $)"]]=scaler.fit_transform(energy_df[["Energy Consumption (MWh)","Cost (Million $)"]])
print("\nData After Standard Scaling:")
print(energy_df)


Data After Standard Scaling:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)  \
0         Solar                 -1.637804         -0.534522   
1          Wind                       NaN          1.603567   
2    Hydropower                  0.589610               NaN   
3    Geothermal                       NaN         -1.069045   
4       Biomass                  0.065512          0.000000   
5       Nuclear                  0.982683               NaN   

   Missing Consumption  Missing Cost  
0                    0             0  
1                    1             0  
2                    0             1  
3                    1             0  
4                    0             0  
5                    0             1  


In [ ]:
# One-hot encode the 'Energy Source' column
energy_encoded_df = pd.get_dummies(energy_df, columns=["Energy Source"])